<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class GigWorkerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create diverse gig workers with different skill sets and experience levels
        $gigWorkers = [
            // Full-Stack Developers
            [
                'first_name' => 'Carlos',
                'last_name' => 'Mendoza',
                'email' => 'carlos.mendoza@developer.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'Senior Full-Stack Developer',
                'bio' => 'Experienced full-stack developer with 5+ years building web applications for Filipino businesses. Specialized in e-commerce platforms, payment integrations, and scalable web solutions. Fluent in English and Filipino.',
                'country' => 'Philippines',
                'city' => 'Manila',
                'phone' => '+639171234568',
                'hourly_rate' => 800.00,
                'broad_category' => 'Web Development',
                'specific_services' => ['Full-Stack Development', 'E-commerce Solutions', 'Payment Integration', 'API Development'],
                'skills_with_experience' => [
                    ['skill' => 'PHP', 'experience_level' => 'expert'],
                    ['skill' => 'Laravel', 'experience_level' => 'expert'],
                    ['skill' => 'JavaScript', 'experience_level' => 'expert'],
                    ['skill' => 'Vue.js', 'experience_level' => 'expert'],
                    ['skill' => 'React', 'experience_level' => 'expert'],
                    ['skill' => 'MySQL', 'experience_level' => 'expert'],
                    ['skill' => 'PostgreSQL', 'experience_level' => 'expert'],
                    ['skill' => 'API Development', 'experience_level' => 'expert'],
                    ['skill' => 'Payment Integration', 'experience_level' => 'expert'],
                    ['skill' => 'AWS', 'experience_level' => 'expert'],
                    ['skill' => 'Docker', 'experience_level' => 'expert'],
                ],
            ],
            [
                'first_name' => 'Michelle',
                'last_name' => 'Garcia',
                'email' => 'michelle.garcia@webdev.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'Full-Stack Web Developer',
                'bio' => 'Passionate web developer with expertise in modern JavaScript frameworks and PHP. Love creating responsive, user-friendly websites that help Filipino businesses grow online. Strong background in e-commerce and CMS development.',
                'country' => 'Philippines',
                'city' => 'Cebu City',
                'phone' => '+639181234568',
                'hourly_rate' => 650.00,
                'broad_category' => 'Web Development',
                'specific_services' => ['Full-Stack Development', 'E-commerce', 'WordPress Development', 'Responsive Design'],
                'skills_with_experience' => [
                    ['skill' => 'PHP', 'experience_level' => 'intermediate'],
                    ['skill' => 'Laravel', 'experience_level' => 'intermediate'],
                    ['skill' => 'JavaScript', 'experience_level' => 'intermediate'],
                    ['skill' => 'Vue.js', 'experience_level' => 'intermediate'],
                    ['skill' => 'MySQL', 'experience_level' => 'intermediate'],
                    ['skill' => 'WordPress', 'experience_level' => 'intermediate'],
                    ['skill' => 'Responsive Design', 'experience_level' => 'intermediate'],
                    ['skill' => 'API Development', 'experience_level' => 'intermediate'],
                    ['skill' => 'Git', 'experience_level' => 'intermediate'],
                ],
            ],

            // Mobile Developers
            [
                'first_name' => 'James',
                'last_name' => 'Reyes',
                'email' => 'james.reyes@mobiledev.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'React Native Mobile Developer',
                'bio' => 'Mobile app developer specializing in React Native and cross-platform development. Created apps for food delivery, e-commerce, and service booking platforms in the Philippines. Expert in integrating local payment methods and push notifications.',
                'country' => 'Philippines',
                'city' => 'Davao City',
                'phone' => '+639191234568',
                'hourly_rate' => 700.00,
                'broad_category' => 'Mobile Development',
                'specific_services' => ['React Native Development', 'Cross-Platform Apps', 'Payment Integration', 'Push Notifications'],
                'skills_with_experience' => [
                    ['skill' => 'React Native', 'experience_level' => 'intermediate'],
                    ['skill' => 'JavaScript', 'experience_level' => 'intermediate'],
                    ['skill' => 'TypeScript', 'experience_level' => 'intermediate'],
                    ['skill' => 'Firebase', 'experience_level' => 'intermediate'],
                    ['skill' => 'Push Notifications', 'experience_level' => 'intermediate'],
                    ['skill' => 'Mobile UI/UX', 'experience_level' => 'intermediate'],
                    ['skill' => 'API Integration', 'experience_level' => 'intermediate'],
                    ['skill' => 'App Store Deployment', 'experience_level' => 'intermediate'],
                ],
            ],
            [
                'first_name' => 'Sarah',
                'last_name' => 'Cruz',
                'email' => 'sarah.cruz@flutter.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'Flutter Mobile Developer',
                'bio' => 'Flutter developer with a passion for creating beautiful, performant mobile applications. Experience in building apps for various industries including healthcare, education, and retail in the Philippine market.',
                'country' => 'Philippines',
                'city' => 'Quezon City',
                'phone' => '+639201234568',
                'hourly_rate' => 600.00,
                'broad_category' => 'Mobile Development',
                'specific_services' => ['Flutter Development', 'Mobile UI/UX', 'Cross-Platform Apps', 'API Integration'],
                'skills_with_experience' => [
                    ['skill' => 'Flutter', 'experience_level' => 'intermediate'],
                    ['skill' => 'Dart', 'experience_level' => 'intermediate'],
                    ['skill' => 'Firebase', 'experience_level' => 'intermediate'],
                    ['skill' => 'SQLite', 'experience_level' => 'intermediate'],
                    ['skill' => 'REST APIs', 'experience_level' => 'intermediate'],
                    ['skill' => 'Mobile UI/UX', 'experience_level' => 'intermediate'],
                    ['skill' => 'State Management', 'experience_level' => 'intermediate'],
                ],
            ],

            // Designers
            [
                'first_name' => 'Mark',
                'last_name' => 'Villanueva',
                'email' => 'mark.villanueva@design.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'Brand Identity & Graphic Designer',
                'bio' => 'Creative graphic designer with 4+ years of experience in brand identity, logo design, and marketing materials. Specialized in creating designs that resonate with Filipino culture while maintaining modern aesthetics. Worked with restaurants, startups, and local businesses.',
                'country' => 'Philippines',
                'city' => 'Iloilo City',
                'phone' => '+639211234568',
                'hourly_rate' => 450.00,
                'broad_category' => 'Creative & Design Services',
                'specific_services' => ['Brand Identity', 'Logo Design', 'Graphic Design', 'Print Design'],
                'skills_with_experience' => [
                    ['skill' => 'Graphic Design', 'experience_level' => 'intermediate'],
                    ['skill' => 'Logo Design', 'experience_level' => 'intermediate'],
                    ['skill' => 'Brand Identity', 'experience_level' => 'intermediate'],
                    ['skill' => 'Adobe Creative Suite', 'experience_level' => 'intermediate'],
                    ['skill' => 'Photoshop', 'experience_level' => 'intermediate'],
                    ['skill' => 'Illustrator', 'experience_level' => 'intermediate'],
                    ['skill' => 'InDesign', 'experience_level' => 'intermediate'],
                    ['skill' => 'Typography', 'experience_level' => 'intermediate'],
                    ['skill' => 'Print Design', 'experience_level' => 'intermediate'],
                ],
            ],
            [
                'first_name' => 'Jenny',
                'last_name' => 'Flores',
                'email' => 'jenny.flores@socialmedia.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'Social Media Designer & Content Creator',
                'bio' => 'Social media specialist and graphic designer creating engaging content for Filipino brands. Expert in current social media trends, visual storytelling, and creating content that drives engagement across Facebook, Instagram, and TikTok.',
                'country' => 'Philippines',
                'city' => 'Baguio City',
                'phone' => '+639221234568',
                'hourly_rate' => 350.00,
                'broad_category' => 'Creative & Design Services',
                'specific_services' => ['Social Media Design', 'Content Creation', 'Video Editing', 'Animation'],
                'skills_with_experience' => [
                    ['skill' => 'Social Media Design', 'experience_level' => 'beginner'],
                    ['skill' => 'Canva', 'experience_level' => 'beginner'],
                    ['skill' => 'Adobe Photoshop', 'experience_level' => 'beginner'],
                    ['skill' => 'Content Creation', 'experience_level' => 'beginner'],
                    ['skill' => 'Animation', 'experience_level' => 'beginner'],
                    ['skill' => 'Video Editing', 'experience_level' => 'beginner'],
                    ['skill' => 'Filipino Culture', 'experience_level' => 'beginner'],
                    ['skill' => 'Trend Analysis', 'experience_level' => 'beginner'],
                ],
            ],

            // Content Writers and Marketers
            [
                'first_name' => 'Patricia',
                'last_name' => 'Santos',
                'email' => 'patricia.santos@writer.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'Content Writer & SEO Specialist',
                'bio' => 'Professional content writer with expertise in SEO, business writing, and Filipino market insights. Created content for various industries including technology, food, travel, and business. Skilled in both English and Filipino content creation.',
                'country' => 'Philippines',
                'city' => 'Makati City',
                'phone' => '+639231234568',
                'hourly_rate' => 400.00,
                'broad_category' => 'Content & Writing',
                'specific_services' => ['Content Writing', 'SEO Writing', 'Business Writing', 'Research'],
                'skills_with_experience' => [
                    ['skill' => 'Content Writing', 'experience_level' => 'intermediate'],
                    ['skill' => 'SEO Writing', 'experience_level' => 'intermediate'],
                    ['skill' => 'Filipino Language', 'experience_level' => 'intermediate'],
                    ['skill' => 'Business Writing', 'experience_level' => 'intermediate'],
                    ['skill' => 'Research', 'experience_level' => 'intermediate'],
                    ['skill' => 'WordPress', 'experience_level' => 'intermediate'],
                    ['skill' => 'Google Analytics', 'experience_level' => 'intermediate'],
                    ['skill' => 'Keyword Research', 'experience_level' => 'intermediate'],
                ],
            ],
            [
                'first_name' => 'Rico',
                'last_name' => 'Dela Rosa',
                'email' => 'rico.delarosa@marketing.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'Digital Marketing Specialist',
                'bio' => 'Digital marketing expert with deep understanding of the Philippine market. Specialized in local SEO, social media marketing, and PPC campaigns. Helped numerous Filipino businesses improve their online presence and reach their target audience.',
                'country' => 'Philippines',
                'city' => 'Taguig City',
                'phone' => '+639241234568',
                'hourly_rate' => 550.00,
                'broad_category' => 'Digital Marketing',
                'specific_services' => ['Digital Marketing', 'Local SEO', 'Social Media Marketing', 'PPC Campaigns'],
                'skills_with_experience' => [
                    ['skill' => 'Digital Marketing', 'experience_level' => 'expert'],
                    ['skill' => 'Local SEO', 'experience_level' => 'expert'],
                    ['skill' => 'Google Ads', 'experience_level' => 'expert'],
                    ['skill' => 'Facebook Ads', 'experience_level' => 'expert'],
                    ['skill' => 'Analytics', 'experience_level' => 'expert'],
                    ['skill' => 'Social Media Marketing', 'experience_level' => 'expert'],
                    ['skill' => 'Email Marketing', 'experience_level' => 'expert'],
                    ['skill' => 'Conversion Optimization', 'experience_level' => 'expert'],
                ],
            ],

            // Virtual Assistants and Administrative
            [
                'first_name' => 'Grace',
                'last_name' => 'Morales',
                'email' => 'grace.morales@va.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'Virtual Assistant & Customer Service Specialist',
                'bio' => 'Experienced virtual assistant with excellent communication skills in English and Filipino. Specialized in customer service, email management, appointment scheduling, and administrative support. Available during Philippine business hours with flexible scheduling.',
                'country' => 'Philippines',
                'city' => 'Antipolo City',
                'phone' => '+639251234568',
                'hourly_rate' => 280.00,
                'broad_category' => 'Administrative Support',
                'specific_services' => ['Virtual Assistance', 'Customer Service', 'Email Management', 'Scheduling'],
                'skills_with_experience' => [
                    ['skill' => 'Virtual Assistance', 'experience_level' => 'intermediate'],
                    ['skill' => 'Customer Service', 'experience_level' => 'intermediate'],
                    ['skill' => 'Email Management', 'experience_level' => 'intermediate'],
                    ['skill' => 'CRM Software', 'experience_level' => 'intermediate'],
                    ['skill' => 'Communication', 'experience_level' => 'intermediate'],
                    ['skill' => 'Time Management', 'experience_level' => 'intermediate'],
                    ['skill' => 'Data Entry', 'experience_level' => 'intermediate'],
                    ['skill' => 'Scheduling', 'experience_level' => 'intermediate'],
                ],
            ],
            [
                'first_name' => 'Daniel',
                'last_name' => 'Aquino',
                'email' => 'daniel.aquino@dataentry.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'Data Entry Specialist & Database Manager',
                'bio' => 'Detail-oriented data entry specialist with expertise in database management and data analysis. Fast and accurate typing skills with experience in various CRM systems, spreadsheet management, and data processing for Filipino businesses.',
                'country' => 'Philippines',
                'city' => 'Las Piñas City',
                'phone' => '+639261234568',
                'hourly_rate' => 220.00,
                'broad_category' => 'Administrative Support',
                'specific_services' => ['Data Entry', 'Database Management', 'Data Analysis', 'Spreadsheet Management'],
                'skills_with_experience' => [
                    ['skill' => 'Data Entry', 'experience_level' => 'beginner'],
                    ['skill' => 'Excel', 'experience_level' => 'beginner'],
                    ['skill' => 'Google Sheets', 'experience_level' => 'beginner'],
                    ['skill' => 'Database Management', 'experience_level' => 'beginner'],
                    ['skill' => 'Attention to Detail', 'experience_level' => 'beginner'],
                    ['skill' => 'Data Analysis', 'experience_level' => 'beginner'],
                    ['skill' => 'CRM Systems', 'experience_level' => 'beginner'],
                    ['skill' => 'Typing Speed', 'experience_level' => 'beginner'],
                ],
            ],

            // Specialized Professionals
            [
                'first_name' => 'Maria Elena',
                'last_name' => 'Ramos',
                'email' => 'mariaelena.ramos@accounting.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'Certified Public Accountant & Bookkeeper',
                'bio' => 'Licensed CPA with 6+ years of experience in accounting, bookkeeping, and tax preparation. Specialized in Philippine tax law, BIR compliance, and financial management for small to medium enterprises. Proficient in various accounting software.',
                'country' => 'Philippines',
                'city' => 'Pasig City',
                'phone' => '+639271234568',
                'hourly_rate' => 500.00,
                'broad_category' => 'Business & Finance',
                'specific_services' => ['Accounting', 'Bookkeeping', 'Tax Preparation', 'Financial Analysis'],
                'skills_with_experience' => [
                    ['skill' => 'Accounting', 'experience_level' => 'expert'],
                    ['skill' => 'Bookkeeping', 'experience_level' => 'expert'],
                    ['skill' => 'QuickBooks', 'experience_level' => 'expert'],
                    ['skill' => 'Tax Preparation', 'experience_level' => 'expert'],
                    ['skill' => 'Financial Analysis', 'experience_level' => 'expert'],
                    ['skill' => 'Philippine Tax Law', 'experience_level' => 'expert'],
                    ['skill' => 'BIR Compliance', 'experience_level' => 'expert'],
                    ['skill' => 'Financial Reporting', 'experience_level' => 'expert'],
                ],
            ],

            // WordPress Specialists
            [
                'first_name' => 'Kevin',
                'last_name' => 'Bautista',
                'email' => 'kevin.bautista@wordpress.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'WordPress Developer & SEO Specialist',
                'bio' => 'WordPress expert with strong SEO knowledge and experience in creating optimized websites for Filipino businesses. Specialized in responsive design, page speed optimization, and local SEO strategies that work in the Philippine market.',
                'country' => 'Philippines',
                'city' => 'Caloocan City',
                'phone' => '+639281234568',
                'hourly_rate' => 420.00,
                'broad_category' => 'Web Development',
                'specific_services' => ['WordPress Development', 'SEO', 'Responsive Design', 'Page Speed Optimization'],
                'skills_with_experience' => [
                    ['skill' => 'WordPress', 'experience_level' => 'intermediate'],
                    ['skill' => 'PHP', 'experience_level' => 'intermediate'],
                    ['skill' => 'SEO', 'experience_level' => 'intermediate'],
                    ['skill' => 'Responsive Design', 'experience_level' => 'intermediate'],
                    ['skill' => 'Google Analytics', 'experience_level' => 'intermediate'],
                    ['skill' => 'Social Media Integration', 'experience_level' => 'intermediate'],
                    ['skill' => 'Page Speed Optimization', 'experience_level' => 'intermediate'],
                    ['skill' => 'Local SEO', 'experience_level' => 'intermediate'],
                ],
            ],

            // UI/UX Designers
            [
                'first_name' => 'Sophia',
                'last_name' => 'Hernandez',
                'email' => 'sophia.hernandez@ux.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'UI/UX Designer',
                'bio' => 'UI/UX designer passionate about creating user-centered designs that work well for Filipino users. Experience in mobile app design, web interfaces, and user research. Understanding of local user behavior and cultural preferences.',
                'country' => 'Philippines',
                'city' => 'Muntinlupa City',
                'phone' => '+639291234568',
                'hourly_rate' => 480.00,
                'broad_category' => 'Creative & Design Services',
                'specific_services' => ['UI/UX Design', 'User Research', 'Wireframing', 'Prototyping'],
                'skills_with_experience' => [
                    ['skill' => 'UI/UX Design', 'experience_level' => 'intermediate'],
                    ['skill' => 'Figma', 'experience_level' => 'intermediate'],
                    ['skill' => 'Adobe XD', 'experience_level' => 'intermediate'],
                    ['skill' => 'User Research', 'experience_level' => 'intermediate'],
                    ['skill' => 'Wireframing', 'experience_level' => 'intermediate'],
                    ['skill' => 'Prototyping', 'experience_level' => 'intermediate'],
                    ['skill' => 'Mobile UI/UX', 'experience_level' => 'intermediate'],
                    ['skill' => 'Responsive Design', 'experience_level' => 'intermediate'],
                ],
            ],

            // Video Editors and Multimedia
            [
                'first_name' => 'Miguel',
                'last_name' => 'Torres',
                'email' => 'miguel.torres@video.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'Video Editor & Motion Graphics Designer',
                'bio' => 'Creative video editor and motion graphics designer with experience in creating engaging content for social media, marketing campaigns, and corporate videos. Familiar with Filipino entertainment preferences and viral content trends.',
                'country' => 'Philippines',
                'city' => 'Marikina City',
                'phone' => '+639301234568',
                'hourly_rate' => 380.00,
                'broad_category' => 'Video & Multimedia',
                'specific_services' => ['Video Editing', 'Motion Graphics', 'Animation', 'Social Media Content'],
                'skills_with_experience' => [
                    ['skill' => 'Video Editing', 'experience_level' => 'intermediate'],
                    ['skill' => 'Motion Graphics', 'experience_level' => 'intermediate'],
                    ['skill' => 'After Effects', 'experience_level' => 'intermediate'],
                    ['skill' => 'Premiere Pro', 'experience_level' => 'intermediate'],
                    ['skill' => 'Animation', 'experience_level' => 'intermediate'],
                    ['skill' => 'Social Media Content', 'experience_level' => 'intermediate'],
                    ['skill' => 'Color Grading', 'experience_level' => 'intermediate'],
                    ['skill' => 'Audio Editing', 'experience_level' => 'intermediate'],
                ],
            ],

            // Junior Developers
            [
                'first_name' => 'Anna',
                'last_name' => 'Perez',
                'email' => 'anna.perez@junior.dev.ph',
                'password' => Hash::make('password123'),
                'user_type' => 'gig_worker',
                'profile_completed' => true,
                'profile_status' => 'active',
                'professional_title' => 'Junior Web Developer',
                'bio' => 'Enthusiastic junior web developer eager to work on exciting projects. Recently completed web development bootcamp and looking to gain more experience. Strong foundation in HTML, CSS, JavaScript, and basic PHP. Quick learner and dedicated to delivering quality work.',
                'country' => 'Philippines',
                'city' => 'San Juan City',
                'phone' => '+639311234568',
                'hourly_rate' => 250.00,
                'broad_category' => 'Web Development',
                'specific_services' => ['Front-End Development', 'Responsive Design', 'Basic Backend'],
                'skills_with_experience' => [
                    ['skill' => 'HTML', 'experience_level' => 'beginner'],
                    ['skill' => 'CSS', 'experience_level' => 'beginner'],
                    ['skill' => 'JavaScript', 'experience_level' => 'beginner'],
                    ['skill' => 'PHP', 'experience_level' => 'beginner'],
                    ['skill' => 'MySQL', 'experience_level' => 'beginner'],
                    ['skill' => 'Responsive Design', 'experience_level' => 'beginner'],
                    ['skill' => 'Git', 'experience_level' => 'beginner'],
                    ['skill' => 'Bootstrap', 'experience_level' => 'beginner'],
                ],
            ],
        ];

        foreach ($gigWorkers as $workerData) {
            // Check if gig worker already exists
            $existingWorker = User::where('email', $workerData['email'])->first();
            
            if ($existingWorker) {
                echo "Gig worker {$workerData['email']} already exists, skipping creation.\n";
            } else {
                User::create($workerData);
                echo "Created gig worker: {$workerData['email']}\n";
            }
        }
    }
}
