[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20', 'postgresql']

[phases.install]
cmds = [
  'composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist'
]

[phases.build]
cmds = [
  'npm ci --legacy-peer-deps',
  'npm run build',
  'php artisan config:clear',
  'php artisan cache:clear'
]

[phases.deploy]
cmds = [
  'php artisan migrate --force --no-interaction',
  'rm -rf public/storage || true',
  'php artisan storage:link --force || true',
  'php artisan optimize:clear',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache',
  'chmod -R 775 storage bootstrap/cache || true'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
